name: Build pipa images
on:
  push:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out build configurations
        uses: actions/checkout@v4

      - name: Create artifact directory
        run: mkdir out

      - name: Install pmbootstrap from git
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          # Patch strict mode off
          sed -i 's/strict: bool = True/strict: bool = False/g' pmbootstrap/pmb/build/_package.py
          sed -i 's/strict: bool = True/strict: bool = False/g' pmbootstrap/pmb/build/backend.py
          pmbootstrap --version

      - name: Copy config and init
        run: |
          mkdir -p ~/.config
          cp xiaomi-pipa.cfg ~/.config/pmbootstrap_v3.cfg
          yes "" | pmbootstrap init

      - name: Build and install
        run: |
          cp xiaomi-pipa.cfg ~/.config/pmbootstrap_v3.cfg
          pmbootstrap install --password 147147
          pmbootstrap export
          cp /tmp/postmarketOS-export/xiaomi-pipa-boot.img out/boot-xiaomi-pipa.img
          cp /tmp/postmarketOS-export/xiaomi-pipa.img out/rootfs-xiaomi-pipa.img

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaomi-pipa-console
          path: out/*.img*
          retention-days: 7
